version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: always
    networks:
      - chatbot_network
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    restart: always
    networks:
      - chatbot_network

networks:
  chatbot_network:
    driver: bridge
